stages:
  - test
  - build
  - deploy

flake8:
  stage: test
  image: python:3.10.8-slim-buster
  before_script:
    - pip install -r requirements.txt
  script:
    - pip install flake8
    - flake8 . --config=flake8.cfg --count --show-source --statistics
  tags:
    - python

run_test:
  stage: test
  image: python:3.10.8-slim-buster
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m pytest